### ISSUE TITLE
Person-Salary <führt durch> <nimmt entgegen>

### ISSUE THREAD

**Issue by NadjaK1** [SiCProD/sicprod-datamodel#29]

**Comment by sennierer** [comment]
ist <wurde ausbezahlt an> und <auf Anweisung von> nicht genau das? Oder gibt es da tatsächlich Aufzeichnungen darüber das ein Bediensteter Geld entgegengenommen hat das für seinen Dienstgeber bestimmt ist?

**Comment by phlaumer** [comment]
Es kommt in den Rechnungsbüchern relativ oft vor, dass Zahlungen durch Mittelsleute abgewickelt werden (Person A erhält einen Sold auf Anweisung von Person B, in deren Auftrag Person C <führt durch> das Geld an Person D <nimmt entgegen> übergibt).
