### ISSUE TITLE
Relation function-salary <führt durch> and <nimmt entgegen>

### ISSUE THREAD

**Issue by phlaumer** [SiCProD/sicprod-datamodel#49]
Also person-salary "führt durch" and "nimmt entgegen"

**Comment by b1rger** [comment]
funktioniert noch nicht

**Comment by b1rger** [comment]
Ergänzungsfrage: solltes es also insgesamt 4 Relationen sein?
```
function <- führt durch -> salary
function <- nimmt entgegen -> salary
person <- führt durch -> salary
person <- nimmt entgegen -> salary
```
(ich hatte bis jetzt 'nimmt entgegen' als das inverse von 'führt durch' gelesen, aber das ergibt ja eigentlich keinen sinn...)

**Comment by phlaumer** [comment]
Korrekt, insgesamt benötigen wir die 4 Relationen. "Führt durch" und "nimmt entgegen" sollen jeweils die Stellvertreter auf beiden Seiten einer Zahlung erfassen.


Viele Grüße

Philipp


________________________________
Von: Birger Schacht ***@***.***>
Gesendet: Dienstag, 21. März 2023 13:08
An: SiCProD/sicprod-datamodel
Cc: Laumer, Philipp Maximilian; Author
Betreff: Re: [SiCProD/sicprod-datamodel] Relation function-salary <führt durch> and <nimmt entgegen> (Issue #49)


Ergänzungsfrage: solltes es also insgesamt 4 Relationen sein?

function <- führt durch -> salary
function <- nimmt entgegen -> salary
person <- führt durch -> salary
person <- nimmt entgegen -> salary


(ich hatte bis jetzt 'nimmt entgegen' als das inverse von 'führt durch' gelesen, aber das ergibt ja eigentlich keinen sinn...)

**Comment by b1rger** [comment]
die 4 relationen sind jetzt implementiert!

**Comment by phlaumer** [comment]
Perfekt, vielen Dank!

________________________________
Von: Birger Schacht ***@***.***>
Gesendet: Mittwoch, 22. März 2023 12:01:50
An: SiCProD/sicprod-datamodel
Cc: Laumer, Philipp Maximilian; Author
Betreff: Re: [SiCProD/sicprod-datamodel] Relation function-salary <führt durch> and <nimmt entgegen> (Issue #49)


die 4 relationen sind jetzt implementiert!
