### ISSUE TITLE
Function-Function-Relation <gehört zu>

### ISSUE THREAD

**Issue by NadjaK1** [SiCProD/sicprod-datamodel#59]

**Comment by b1rger** [comment]
Wenn `A gehört zu B` - folgt daraus `B gehört zu A` (also gleichwertig)? Oder soll dann folgen `B ist A übergeordnet` (also eine Hierarchie)?
Es gibt auch `ist untergeordnet`, ist `gehört zu` etwas anderes?

**Comment by NadjaK1** [comment]
Gedacht hätte ich es als Spezifizierung, also gleichwertig. Mein konkretes Beispiel kommt aus dem Handwerksbereich: Wir haben als Funktion den Werkmeister, wo es verschiedene gibt, man aber oft aus den Quellen nicht herausliest, um was für einen Werkmeister es sich handelt. Nun weiß ich aber in einem konkreten Fall, dass eine Person Werkmeister des Wassers war. :)

**Comment by b1rger** [comment]
Und es wäre dann in Worten *Werkmeister des Wassers gehört zu Werkmeister*? Aber es wäre ja nicht andersrum (*Werkmeister gehört zu Werkmeister des Wassers*), oder?

Also gibt es die Funktion `Werkmeister` und darunter gibt es mehrere gleichwertige Spezifizierungen (Wasser, Stein, ...)?

(Ich muss mir nur immer auch eine Bezeichnung für die Rückrelation überlegen, daher die Fragen - ich schätze *Werkmeister des Wassers gehört zu Werkmeister* ist gleich mit *Werkmeister ist übergeördnet Werkmeister des Wassers*)

**Comment by b1rger** [comment]
wird ersetzt durch #64
