### ISSUE TITLE
personen duplizieren: zotero referenzen werden nicht übernommen

### ISSUE THREAD

**Issue by b1rger** [SiCProD/sicprod-datamodel#67]

**Comment by b1rger** [comment]
Ich kann das leider nicht reproduzieren, ich habe soeben die person `Test Entity` dupliziert und die Referenz auf die Person wurde bei dem Duplikat mitkopiert. @NadjaK1 kannst du das nochmal probieren oder mir einen konkreten Fall sagen, wo es nicht funktioniert?

**Comment by NadjaK1** [comment]
Habe Weineck, Hildebrand von (ID 949) kopiert in Weineck, Hildebrand von (ID 6864) und noch nichts verändert. Bei ID 949 sind einige Zotero-Zitate vorhanden, bei 6864 auf den ersten Blick keines übernommen.

**Comment by b1rger** [comment]
Ah, du beziehst dich nicht auf die Zitate direkt auf die Person (weil die sehe ich bei beiden) - sondern auf die Zitate der Relationen? Zum Beispiel `Urkundenreihe 1` bei der Relation `22.5.1446 + hat Funktion inne + Pfleger zu Leuchtenburg` ist beim Duplikat nicht vorhanden...

**Comment by NadjaK1** [comment]
Ja genau!

**Comment by b1rger** [comment]
Es werden jetzt auch die Referenzen der Relationen übernommen
