### ISSUE TITLE
Additonal types of places

### ISSUE THREAD

**Issue by MDebertol** [SiCProD/sicprod-datamodel#9]
Lehen/Herrschaft; Haus/Hof... (müssen wir noch besprechen)

**Comment by NadjaK1** [comment]
Stadt
Dorf/Nachbarschaft/Gemein/Siedlung/Weiler
Burg/Schloss
Land/Herrschaftskomplex
Landschaft/Region
Lehen
Haus/Hof
Gericht
Kloster
Gewässer
Grundherrschaft
Hofmark
Tal
Berg
Bergrevier
Pflege
(Land-)Vogtei
Propstei
